server:
  port: 9999

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/gdcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 5
      max-open-prepared-statements: 10